### ISSUE TITLE
Spring boot microservices example

### ISSUE THREAD

**Issue by Jdruwe** [kucharzyk/vuejs-java-starter#2]
Hey, I was wondering if you were planning on an example as in your: https://github.com/kucharzyk/spring-angular2-starter. But using vuejs instead of angularjs?

**Comment by kucharzyk** [comment]
I'm currently not planing such example for vue.js (maybe for vue.js 2.0), 

It should be easy to combine this two examples and use vue,js as frontend. Try to combine them.

Use angular starter as base and replace frontend to vue.js
